services:
  udap.authserver.devdays:
    image: ${DOCKER_REGISTRY-}udapauthserverdevdays
    build:
      context: .
      dockerfile: udap.authserver.devdays/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - UdapIdpBaseUrl=https://host.docker.internal:5102
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/udap-tutorial-dev-tls-cert.pfx
    ports:
      - "5102:8081"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https:ro

  udap.certificates.server.devdays:
    image: ${DOCKER_REGISTRY-}udapcertificatesserverdevdays
    build:
      context: .
      dockerfile: udap.certificates.server.devdays/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5034:8080"

  udap.fhirserver.devdays:
    image: ${DOCKER_REGISTRY-}udapfhirserverdevdays
    build:
      context: .
      dockerfile: udap.fhirserver.devdays/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/udap-tutorial-dev-tls-cert.pfx
    ports:
      - "5017:8080"
      - "7017:8081"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https:ro

  udap.idp.server.devdays:
    image: ${DOCKER_REGISTRY-}udapidpserverdevdays
    build:
      context: .
      dockerfile: udap.idp.server.devdays/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - UdapIdpBaseUrl=https://host.docker.internal:5202
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/udap-tutorial-dev-tls-cert.pfx
    ports:
      - "5202:8081"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https:ro

  udaped:
    image: ghcr.io/joeshook/udaped:v0.4.4.30
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/udap-tutorial-dev-tls-cert.pfx      
    ports:
      - "7041:8081"
      - "5171:8080"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https:ro
      - ./CertificateStore:/app/CertificateStore:ro

    
