services:
  udap.authserver.devdays:
    image: ghcr.io/joeshook/udapauthserverdevdays:latest
    environment:
      - ASPNETCORE_HTTPS_PORTS=8081
      - UdapIdpBaseUrl=https://host.docker.internal:5102
      - ASPNETCORE_Kestrel__Certificates__Default__Password=udap-test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/udap-tutorial-dev-tls-cert.pfx
    ports:
      - "5102:8081"
    volumes:
      - ./CertificateStore:/home/app/.aspnet/https:ro

  udap.certificates.server.devdays:
    image: ghcr.io/joeshook/udapcertificatesserverdevdays:latest
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5034:8080"

  udap.fhirserver.devdays:
    image: ghcr.io/joeshook/udapfhirserverdevdays:latest
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=udap-test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/udap-tutorial-dev-tls-cert.pfx
    ports:
      - "5017:8080"
      - "7017:8081"
    volumes:
      - ./CertificateStore:/home/app/.aspnet/https:ro

  udap.idp.server.devdays:
    image: ghcr.io/joeshook/udapidpserverdevdays:latest    
    environment:
      - ASPNETCORE_HTTPS_PORTS=8081
      - UdapIdpBaseUrl=https://host.docker.internal:5202
      - ASPNETCORE_Kestrel__Certificates__Default__Password=udap-test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/udap-tutorial-dev-tls-cert.pfx
    ports:
      - "5202:8081"
    volumes:
      - ./CertificateStore:/home/app/.aspnet/https:ro

  udaped:
    image: ${DOCKER_REGISTRY-}udaped-tutorial
    build:
      context: .
      dockerfile: Dockerfile.UdapEd
    environment:
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=udap-test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/udap-tutorial-dev-tls-cert.pfx      
    ports:
      - "7041:8081"
    volumes:
      - ./CertificateStore:/home/app/.aspnet/https:ro
      - ./CertificateStore:/app/CertificateStore:ro
      - ./Packages:/app/wwwroot/Packages:ro

    
