name: Build Docker Images

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Tag'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: Convert repository name to lowercase
      id: to_lowercase
      run: echo "::set-output name=lower_repo::${GITHUB_REPOSITORY,,}"


    - name: Build and push udap.authserver.devdays Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./udap.authserver.devdays/Dockerfile
        push: true
        tags: ghcr.io/${{ steps.to_lowercase.outputs.lower_repo }}:${{ github.event.inputs.name }}


    - name: Build and push udap.certificates.server.devdays Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./udap.certificates.server.devdays/Dockerfile
        push: true
        tags: ghcr.io/${{ steps.to_lowercase.outputs.lower_repo }}:${{ github.event.inputs.name }}


    - name: Build and push udap.fhirserver.devdays Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./udap.fhirserver.devdays/Dockerfile
        push: true
        tags: ghcr.io/${{ steps.to_lowercase.outputs.lower_repo }}:${{ github.event.inputs.name }}


    - name: Build and push udap.idp.server.devdays Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./udap.idp.server.devdays/Dockerfile
        push: true
        tags: ghcr.io/${{ steps.to_lowercase.outputs.lower_repo }}:${{ github.event.inputs.name }}
  
  

